"use client"

import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/ui/tabs"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card"
import { TranscriptView } from "./transcript-view"
import { VocabularyList } from "./vocabulary-list"
import { type TranscriptItem } from "@/ai/flows/process-video-flow"
import { BrainCircuit, BookOpenText, List } from "lucide-react"

type VideoTabsProps = {
  transcript: TranscriptItem[];
  videoId: string;
};

function AiInsightsTab() {
    return (
        <Card>
            <CardHeader>
                <CardTitle className="flex items-center gap-2">
                    <BrainCircuit />
                    AI Insights
                </CardTitle>
                <CardDescription>
                    A summary and key takeaways from the video, generated by AI.
                </CardDescription>
            </CardHeader>
            <CardContent>
                <div className="space-y-4">
                     {/* This is a placeholder. In a real implementation, you would fetch and display AI-generated insights. */}
                    <div className="p-4 border rounded-lg bg-secondary/50">
                        <h3 className="font-semibold text-lg mb-2">Summary</h3>
                        <p className="text-muted-foreground">AI-generated summary of the video will appear here. This feature is coming soon.</p>
                    </div>
                     <div className="p-4 border rounded-lg bg-secondary/50">
                        <h3 className="font-semibold text-lg mb-2">Learning Takeaways</h3>
                        <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                            <li>Key learning point 1 will be listed here.</li>
                            <li>Key learning point 2 will be listed here.</li>
                            <li>Key learning point 3 will be listed here.</li>
                        </ul>
                    </div>
                </div>
            </CardContent>
        </Card>
    )
}


export function VideoTabs({ transcript, videoId }: VideoTabsProps) {
  return (
    <Tabs defaultValue="transcript" className="w-full">
      <TabsList className="grid w-full grid-cols-3">
        <TabsTrigger value="insights"><BrainCircuit className="h-4 w-4 mr-2"/> Insights</TabsTrigger>
        <TabsTrigger value="transcript"><BookOpenText className="h-4 w-4 mr-2"/>Transcript</TabsTrigger>
        <TabsTrigger value="vocabulary"><List className="h-4 w-4 mr-2"/>Vocabulary</TabsTrigger>
      </TabsList>
      <TabsContent value="insights">
        <AiInsightsTab />
      </TabsContent>
      <TabsContent value="transcript">
        <Card>
            <CardHeader>
                <CardTitle className="flex items-center gap-2">
                    <BookOpenText />
                    Transcript
                </CardTitle>
                <CardDescription>
                    Click a word to add it to your vocabulary list.
                </CardDescription>
            </CardHeader>
            <CardContent>
                <TranscriptView transcript={transcript} videoId={videoId} />
            </CardContent>
        </Card>
      </TabsContent>
      <TabsContent value="vocabulary">
        <Card>
            <CardHeader>
                <CardTitle className="flex items-center gap-2">
                    <List />
                    Vocabulary
                </CardTitle>
                 <CardDescription>
                    Your saved words for all videos.
                </CardDescription>
            </CardHeader>
            <CardContent>
                <VocabularyList />
            </CardContent>
        </Card>
      </TabsContent>
    </Tabs>
  )
}
